### ISSUE TITLE
Custom electronProjectPath

### ISSUE THREAD

**Issue by DuBistKomisch** [adopted-ember-addons/ember-electron#1011]
Hi, we're trying to migrate a large existing project from custom scripts to use `ember-electron`. Our existing folder was called `electron/`, but `ember-electron` seems to be hardcoded to use `electron-app/`. Renaming the folder is quite disruptive to other open PRs and the git history, so I was wondering if it's possible to use a custom path?

I can see in `lib/utils/build-paths.js` that it's simply hard coded as a string, and changing it locally seems to work. Maybe this could be passed as an `ember install` argument and stored somewhere in the ember level.

**Comment by rwwagner90** [comment]
I think `electron-app` is the path used by electron forge. Is that correct @bendemboski?

**Comment by bendemboski** [comment]
I think that path is used in two contexts (other than unit tests):

1. From the blueprint and `electron-forge` template (which is invoked from the blueprint) when setting up a project
2. From various `ember-cli` commands (including the `test-runner.js` that is outside the `ember-cli` process, but is invoked from the `electron:test` command)

To make (1) work, we'd have to add an argument to the blueprint like you mention so the blueprint can generate everything in a different directory, and then emit some information that will tell (2) where that different directory is when running commands. Or we could punt on (1) and make the workflow for your use case be to run the default blueprint, rename `electron-app` to whatever you want, and manually apply some configuration to the project to inform (2) of that new directory.

To make (2) work, I think we'd probably want to use `ember-cli` configuration, probably `ember-cli-build.js` to configure the Electron project path. This works in principle, because all of (2) is invoked from `ember-cli` commands, so logically has access to the `ember-cli` build config, but the mechanics of ensuring that all the current code locations that consume the project path do is probably non-trivial -- figuring out how to pass information down from explicity `ember-cli`-aware code to utility code that isn't currently passed `ember-cli` objects like the project that would provide automatic access to this configuration. I suppose we could have `ember-electron`'s `index.js` read the configuration and set an environment variable, `process.env.EMBER_ELECTRON_PROJECT_PATH` or something, similar to how `ember-cli` sets `EMBER_ENV` so addon code can always easily access the current build environment target.

Those are my thoughts -- we'd definitely entertain a PR!

**Comment by DuBistKomisch** [comment]
Thanks for the detailed response! After thinking about it some more, I'll probably just wait until there's no conflicting PRs open and just deal with the merge. It's probably not worth this much effort for what's really a one-off problem.

**Comment by bendemboski** [comment]
That makes sense to me. We haven't heard anyone else ask for this, so it does seem pretty one-off right now, although I do kinda like the notion of being able to put the Electron app in a separate git repo so it's not even inside the Ember repo/project, which I think something like this should unlock. But I don't like it enough to go do the work to make it happen right now 😄 

Anyway, good luck with the migration to `ember-electron`! If you run into any issues, you can also go and post in the `#topic-desktop` channel in Ember Discord to get in touch with us and other folks that have experience with `ember-electron`.

**Comment by DuBistKomisch** [comment]
Quick update in case anyone is interested: I ended up using `patch-package` to override the `electronProjectPath`. We only really care about the main `npx ember electron` command, where it seems to work. I haven't tried `electron:test` since we have our own unit test system using spectron.

**Comment by rwwagner90** [comment]
@DuBistKomisch perhaps documenting your setup in our docs could be useful to others?

**Comment by DuBistKomisch** [comment]
I suppose I could add it as an FAQ, if you think that makes sense, any suggestions on which section?

**Comment by rwwagner90** [comment]
@DuBistKomisch perhaps here? https://ember-electron.js.org/docs/guides/structure

I think this counts as structure, since it's using a different path.

**Comment by bendemboski** [comment]
> @DuBistKomisch perhaps here? https://ember-electron.js.org/docs/guides/structure

I agree -- I think adding a section to the end of that page makes sense, maybe something like `Customizing the location of the Electron application`
