### ISSUE TITLE
Idiomatic way to open a route in a new window?

### ISSUE THREAD

**Issue by artsyca** [adopted-ember-addons/ember-electron#1194]
Guys, let me start off by saying you are pioneers way ahead of the curve and I really appreciate your hard work here laying the groundwork for us!

I'm at that stage in the learning curve where I'm still trying to catch up with the latest advances in Ember CLI not to mention electron and ember-electron but I'm in a situation where I need multiple windows in my app that would ideally share state and  be able to communicate amongst themselves.

I'm not a total noob, but I'm still coming to terms with 'data down actions up' and now there's a whole new layer to the onion so to speak (i.e. the node layer). I'd like to ask if there's a consensus on the best practices approach to launching routes in new windows? Should it be done in the ember layer with `window.open` somehow, or should a signal be sent to electron via `requireNode`? I'd really be interested in a full example that includes all of the important details.

Very much obliged!

**Comment by rwwagner90** [comment]
Can you give an example of what these routes might do and what data they should share? I think I might recommend using something like `ipcRenderer.send` on the Ember side to trigger the Electron code you need.

**Comment by artsyca** [comment]
Yes!

We’re building a courseware application where the instructors share a
window on zoom. They have a window with a lesson plan which launches window
for the students with images, videos, a whiteboard or games. Ideally I’d
like to have it all running as one app with multiple windows that can
potentially share state and data as opposed to multiple instances of the
app running in discrete windows.

**Comment by bendemboski** [comment]
What is your app's data model? Is there a server that stores the data/lesson plans/etc.? Or is it all local/on the instructors' hard drives?

**Comment by artsyca** [comment]
Wow, Ben, your question is 👉🏻👃🏼 on the nose!

It's a hybrid model I'd like to say. At present it's all local running on the `file://` protocol (hence the idea to use Electron) but we want to begin the process of migrating to something more CMS-driven and use the app as a frontend for it.

There isn't a terrible amount of state being shared between windows just for instance clicking on an image and having it load into an image viewer or having a list of flashcards and loading them into a game. I think I understand where you're heading, and I think it's fair play to reload data as needed from the server. Primarily now I want to understand how to just open another app instance in a new window at a chosen route with the minimum of complexity.

I saw a solution that just uses `window.open` but it seemed rather hard to get the absolute app url so I was wondering if there was some kind of call we needed to make. The `ipcRenderer` seems promising but I'd be grateful for a comprehensive example.

To give you an idea, I didn't even know it was possible or even idiomatic to declare something like

```
const { IpcRenderer } = requireNode('electron');
```

That already seems like dark magic to me.

**Comment by bendemboski** [comment]
Yeah, Electron IPC is the way to go here I think. This doesn't have a lot to do with Ember, it's really all about Electron, so I'd probably start be perusing Electron's [IPC documentation](https://www.electronjs.org/docs/latest/tutorial/ipc).

What you're asking is really an (Electron) application architecture question, and I don't really know of anything idiomatic that would help you, but I can tell you how I'd do it.

I would set up the main process as a sort of window manager. For example, if you have a "singleton" window like the image viewer, then when the user clicks on an image that window may or may not already be open, and it would be nice for the renderer process (Ember app) to not have to worry about it. So it could send a message to the main process saying "show image window" and the main process would know if the image window was already open, and either open it or focus it depending. This would look something like this (I haven't tested or anything so there are certainly going to be errors in this code):

```js
// electron-app/src/index.js
const { app, ipcMain, BrowserWindow } = require('electron');
const { pathToFileURL } = require('url');

const emberAppURL = pathToFileURL(
  path.resolve(__dirname, '..', 'ember-dist', 'index.html')
);

let imageWindow;

function showImageWindow() {
  if (imageWindow) {
    imageWindow.focus();
    return;
  }

  imageWindow = new BrowserWindow(...);
  imageWindow.on('closed', () => {
    imageWindow = null;
  });
  // assuming `/image-viewer` is the URL path of the Ember route that
  // implements the image viewer
  imageWindow.loadUrl(`${emberAppURL}#image-viewer`);
}

app.on('ready', () => {
  ipcMain.on('showImageWindow', showImageWindow);
});
```

```js
// somewhere in your Ember app
@action
openImageWindow() {
  const { ipcRenderer } = requireNode('electron');
  ipcRenderer.send('showImageWindow');
}
```

Then you have some basic window management. If you have multiple singleton windows, you could change `imageWindow` to a map or object or something, so you have

```js
let windows = {};

function showWindow(name) {
  if (windows[name]) {
    windows[name].focus();
    return;
  }

  windows[name] = new BrowserWindow(...);
  // etc
}
```

Then you have to worry about data management. All the windows can maybe fetch server-side data from the server and that could be fine. But the image window presumably needs to know what image to display. There are a number of options for that. For example, you could use `localStorage` or `IndexedDB`. So the Ember code in the "primary" window pushes some info about the image to view into `localStorage` before doing the `ipcRendered.send('showImageWindow')`. Then the image viewer Ember route (running in the image viewer window) can check that `localStorage` key when it first loads, and also set up an observer so that when another image is selected, it gets an event and can display that image.

Another option would be to use IPC for it, so along with the `showImageWindow` command you can pass whatever info is needed to indicate the image to display. Then the main process, after focusing or opening the window, would do `imageWindow.webContents.send('viewImage', imageInfo)` or something. The image viewer route would have had to do `ipcRenderer.on('viewImage', (event, imageInfo) => this.shownImage = imageInfo)`. But that gets a little sticky because of timing -- if the main process sends the event too early the Ember app might still be loading and not have set up the IPC listener. Maybe you solve that by sticking the image info in a query param when first opening the window, but sending an IPC command if the window is already open. Or maybe you always use a query param and call `imageWindow.loadUrl()` very single time, which would mean that "switching" images would be a full page load/Ember app reload, rather than just a "command" sent to the already-running Ember app to tell it to display different data. But I'm kinda getting off into the weeds here.

Hope this is helpful!

**Comment by artsyca** [comment]
@bendemboski I'm so grateful for this insightful and complete explanation. It's exactly what I've been looking for.

You're right. We're at the intersection of the ember/electron idioms so we're looking for something that fits in without creating unnecessary ripples.

I think the indexedDb solution is pretty good and so is localstorage. In our case it may be as simple as passing a parameter to the window but it's great to have options.

Just out of pure curiosity I'd be interested to design a solution that gives all windows access to the same store, but that's just a thought experiment at this point.

Sincerely appreciate your help on this. I'll post an update once we give it a spin.

**Comment by rwwagner90** [comment]
You could also use Orbit.js for data management. It will work with just IndexedDB if you want and allows you to add on other sources later if needed.
