### ISSUE TITLE
Can't generate AppImage

### ISSUE THREAD

**Issue by thiagocardoso1988** [adopted-ember-addons/ember-electron#406]
When executing  `ember electron:package`, it does generate the electron-out folder as expected, but there is no executable in the folder for me to run.

How am I supposed to run the app then? My goal is to generate a standalone file to be used, without installation.

This behavior is achieved using plain electron.

`electron-out` folder content:
```
electron-out$ ls -la
total 16
drwxrwxr-x  4 thiago thiago 4096 Nov 14 17:05 .
drwxrwxr-x 15 thiago thiago 4096 Nov 14 16:36 ..
drwxrwxr-x  4 thiago thiago 4096 Nov 14 16:47 project
drwxrwxr-x  5 thiago thiago 4096 Nov 14 17:05 shopper-linux-x64
```

Inside the shopper folder:
```
electron-out/shopper-linux-x64$ ls -la
total 151088
drwxrwxr-x 5 thiago thiago      4096 Nov 14 17:05 .
drwxrwxr-x 4 thiago thiago      4096 Nov 14 17:05 ..
-rw-r--r-- 1 thiago thiago    167930 Nov 14 17:05 chrome_100_percent.pak
-rw-r--r-- 1 thiago thiago    250097 Nov 14 17:05 chrome_200_percent.pak
-rw-r--r-- 1 thiago thiago  10218000 Nov 14 17:05 icudtl.dat
-rwxr-xr-x 1 thiago thiago    255912 Nov 14 17:05 libEGL.so
-rwxr-xr-x 1 thiago thiago   3152384 Nov 14 17:05 libffmpeg.so
-rwxr-xr-x 1 thiago thiago   6058008 Nov 14 17:05 libGLESv2.so
-rwxr-xr-x 1 thiago thiago   7199112 Nov 14 17:05 libVkICD_mock_icd.so
-rw-r--r-- 1 thiago thiago      1060 Nov 14 17:05 LICENSE
-rw-r--r-- 1 thiago thiago   1993542 Nov 14 17:05 LICENSES.chromium.html
drwxrwxr-x 2 thiago thiago      4096 Nov 14 17:05 locales
-rw-r--r-- 1 thiago thiago    125011 Nov 14 17:05 natives_blob.bin
drwxrwxr-x 3 thiago thiago      4096 Nov 14 17:05 resources
-rw-r--r-- 1 thiago thiago   8691078 Nov 14 17:05 resources.pak
-rwxr-xr-x 1 thiago thiago 114866176 Nov 14 17:05 shopper
-rw-r--r-- 1 thiago thiago    641676 Nov 14 17:05 snapshot_blob.bin
drwxrwxr-x 2 thiago thiago      4096 Nov 14 17:05 swiftshader
-rw-r--r-- 1 thiago thiago   1040376 Nov 14 17:05 v8_context_snapshot.bin
-rw-r--r-- 1 thiago thiago         5 Nov 14 17:05 version
```

**Comment by bendemboski** [comment]
What OS?

**Comment by bendemboski** [comment]
Ah, linux. Isn't `shopper` what you're looking for?

**Comment by thiagocardoso1988** [comment]
@bendemboski my OS is Ubuntu 16.04

**Comment by thiagocardoso1988** [comment]
> Ah, linux. Isn't `shopper` what you're looking for?

It isn't, since it is a folder. I am looking for a way to execute the packed app, like I have using plain electron, it gives a `.appimage` file, that I can execute

**Comment by thiagocardoso1988** [comment]
if I run `./shopper` it does execute, but I'm asking if I can package it as an `.appimage`

**Comment by bendemboski** [comment]
Unfortunately I don't think that's possible directly from `ember-electron` now. `ember-electron` is built on top of [electron-forge](https://github.com/electron-userland/electron-forge/tree/v5.2.4), v5, and it does not appear to have support for appimage.

Unfortunately `electron-forge` has been in a transitional state, with v6 in beta, for some time now, so it's a little hard to find documentation outside the README on github (if you go to the v5.2.4 branch as in the link above), but here's a quick summary:

What you are asking about is, in the language of `electron-forge`, a maker. The packaged app is a just the set of resources you see above, and the job of makers is to bundle it up into an installer, or similar. You can see makers for DMGs on MacOS, or squirrel installers on Windows, etc. It has built-in `deb`, `rpm`, `flatpak`, and `snap` makers for linux. [electron-forge-maker-appimage](https://www.npmjs.com/package/electron-forge-maker-appimage) exists on npm, but given that it's not documented and its GitHub links just point to `electron-builder`, I highly doubt it's functioning, especially not on `electron-forge` v5.

So you could try implementing a maker yourself (`electron-forge`'s maker system is pluggable) that uses `app-builder-lib` or something to build an appimage, but my advice would be not to go that route because the tooling is currently in such an odd and transitional state. If none of the built-in makers meet your needs, I'd advise just rolling the appimage yourself in a post-`electron package` build step.

I'm going to close this issue, since it's not an issue with `ember-electron` per se, but really with `electron-forge` (but feel free to keep asking questions here and I'll respond as I can, or better yet, ask in the `#topic-desktop` room in Ember community discord).
