### ISSUE TITLE
3.x changes electron appPath during tests

### ISSUE THREAD

**Issue by jacobq** [adopted-ember-addons/ember-electron#428]
```js
requireNode('electron').remote.app.getAppPath();
// Returns 'path/to/app/electron-app' in dev (presumably similar in prod?)
// Returns 'path/to/app/electron-app/tests' in test
```
Is this intentional / necessary? I don't believe this was the case in 2.x (it's one of the things that broke when I migrated to 3.0.0-beta.0)

**Comment by bendemboski** [comment]
Hmm...I guess this is happening because Electron does something kinda annoying in `getAppPath()` as explained [here](https://github.com/electron/electron/issues/10975#issuecomment-340660249).

When running tests we try to mimic the app environment as closely as possible, and since we no longer have the assemble phase of the build pipeline where we copy a bunch of files around to create an electron-forge project, that means `index.js` for the tests lives inside the electron-forge project, i.e. inside `electron-app`.

When we run `ember electron`, we point Electron to `electron-app/` and it finds the `package.json` there, which points it to `src/index.js` to run the main process. But according to my reading of the above, since it found the `package.json`, it treats the directory where it found it as the app directory. But when we run tests, since we only have one `package.json`, we have to point it directly at `tests/index.js`, which apparently sets the app directory to be inside `tests/`.

So I see three options:

1. Live with it as it is and include information about it in the guide (to-be-written)
2. Move the test `index.js` to the root of the project so the app directories would be the same (but I'm pretty sure this would mess up some other things since, e.g., now the path to `electron-app/resources` would be `../resources` from `index.js` and `./resources` from the test `index.js`)
3. Possibly write a [plugin](https://www.electronforge.io/advanced/extending-electron-forge/writing-plugins#gethook-hookname-string-function) that uses the `readPackageJson` hook to override the `main` entry in `package.json` when running tests so we can launch the same way as when running `ember-electron`, but point it to `tests/index.js` instead of `src/index.js`.

The last one seems like maybe the cleanest if it actually works.

**Comment by jacobq** [comment]
My sloppy solution for now was to use my own util instead:

```js
const { sep, resolve } = requireNode('path');

export function getElectronAppPath() {
    const appPath = requireNode('electron').remote.app.getAppPath();
    const segments = appPath.split(sep);
    if (segments[segments.length - 1] === 'tests') {
        segments.pop();
    }
    return segments.join(sep);
}
```

**Comment by bendemboski** [comment]
I generally use `__dirname` and relative paths for accessing paths within the application, so might be easier for you to use that instead of `getAppPath()`?

**Comment by jacobq** [comment]
I'll check it out. (For one thing, it'd let me drop another `remote` call.) I think I had some misunderstanding of how `__dirname` worked and got burned once by it changing based on whether running from `electron path/to/app` vs. packaged with ASAR.... can't remember what went wrong

**Comment by jacobq** [comment]
Closing since I'm going with "option 1" (just accepting this behavior and coding around it) though I agree that a plugin to make dev/prod and test match would be ideal.
