### ISSUE TITLE
ember electron:make with output-path

### ISSUE THREAD

**Issue by basz** [adopted-ember-addons/ember-electron#636]
Running `ember electron:make` from the ember root directory builds an application of ~330 Mb and stores it in `./electron-app/out`.

But when *make* with `ember electron:make --output-path=./builds` the application becomes ~1.2Gb.

Inspecting the package content (macOS) it seems the whole node_directory of the ember project has been added to the build. That seems not unneeded as the ember app builds before electron forge runs.

Also, the app doesn't runs... 😀  which doesn't surprise me...

running with (but came from `ember install ember-electron:.3.0.0-beta.3`)
"ember-electron": "https://github.com/adopted-ember-addons/ember-electron#master",

**Comment by rwwagner90** [comment]
@basz I have not tried passing that option. Is there a reason you can't use `./electron-app/out`? You could have a script that moves that if you need to.

**Comment by basz** [comment]
`./electron-app/out` is fine. Just seemed like a scoping bug somehow.

**Comment by rwwagner90** [comment]
It certainly could be. @bendemboski any ideas here?

**Comment by bendemboski** [comment]
Huh, that's weird, I haven't seen that. I wonder if `electron-forge` gets confused if the output directory is outside the electron-forge project (because the only thing the make command does with that output directory option is forward it to the electron-forge make API method).

**Comment by basz** [comment]
I was wondering that too, so I tried `ember electron:make --output-path=./electron-app/builds` which indeed builds to `electron-app/builds` but with the same non functional application.

**Comment by bendemboski** [comment]
Oh, well I think I have a pretty good guess as to why your app size is inflated a whole bunch. When you run `ember electron:make --output-path=./electron-app/builds` you still have your `electron-app/out` directory containing everything you previously built.

`electron-packager` accepts an ignore list instead of an include list for the files in your application (in our case, `electron-app`) that it packages up, which is really annoying because then you have to maintain a list of all files/dirs you _don't_ want included in the packaged application rather than the files you _do_ want.

`electron-forge` defaults the output directory of its built assets to `./out`, meaning they end up in your application.

`electron-packager` automatically ignores the output directory when packaging, so as long as you just keep packaging into the same directory you're fine. But (I think), in your case, you packaged into the default `electron-app/out` directory, and then later packaged into a different directory, meaning that `electron-packager` didn't auto-ignore your `electron-app/out` directory (because it's not the output directory) and included it in your packaged application.

I'm pretty confident that this is actually an issue with the integration between `electron-forge` and `electron-packager` -- if you used `electron-forge` to create a vanilla non-Ember application, then ran `electron-forge make`  and then used `electron-forge`'s API to make again with a different output directory (the CLI doesn't allow you to specify a different output directory, which is maybe why this issue hasn't come up before) you'll end up bundling the previously-built `out` directory in the second packaged application.

You could either delete the `out` directory before making, or you could add `out` to the ignore list in your `electron-forge-config.js` (which #638 will do automatically for new `ember-electron` apps).

However, none of this explains the app's inability to launch -- I can't think of why having an `out` directory with a bunch of random stuff in your packaged application would cause problems. When I run the same scenario, my super-bloated application package launches and runs just fine. Can you provide more details on why the app isn't running?

**Comment by basz** [comment]
yes! confirmed.

Removing 'out' reduced the file size. Also, the non-starting app was due to some missing dependency.

Thanks!
