### ISSUE TITLE
requireNode is not a function even with nodeIntegration turned on

### ISSUE THREAD

**Issue by dtolios** [adopted-ember-addons/ember-electron#763]
I just upgraded my app to ember-electron v3 and am having trouble getting "requireNode" working in my app. I have the following set in my index.js:

```
mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
    },
  });
```

I'm still having a problem the moment I launch my app because "requireNode is not a function". 

If i switch that to "require" I still get the same error, but coming from the ember-electron vendor script. 

Any tips or help is greatly appreciated as usual :)

**Comment by rwwagner90** [comment]
@dtolios did you follow all the instructions here? https://ember-electron.js.org/docs/guides/upgrading

**Comment by dtolios** [comment]
I did run that, but to verify I also spun up a new ember app doing the following:

1. Opened terminal in my projects/ dir
1. ran `ember new ember-electron-test`
1. ran `ember install ember-electron`
1. added the webPreferences with nodeIntegration to my main.js file
1. added a component which called requireNode("electron")
1. ran `ember electron`
1. saw error in my console

With that said, I've also been reading that I can wrap what I need using a preload script, but I'm also having a bit of trouble there, because the script doesn't seem to be run.

**Comment by rwwagner90** [comment]
What file are you using `requireNode` in?

**Comment by dtolios** [comment]
It was a component file located in:
```
app/
  components/
    my-button.js
```

**Comment by dtolios** [comment]
Just a quick update, I was able to get around this in what I think is a nicer way this morning by using a preload script to wrap APIs. Here's what I did:

```
// in index.js of my electron app

// code...
mainWindow = new BrowserWindow({
    width: 1280,
    height: 720,
    frame: false,
    resizable: false,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
    },
  });

// code...

  ipcMain.on("minimize", () => {
    mainWindow.minimize();
  });

  ipcMain.on("quit", () => {
    app.quit();
  });
```

```
// in preload.js
const { contextBridge, ipcRenderer, shell } = require("electron");

contextBridge.exposeInMainWorld("electron", {
  myOpenExternal: (url) => shell.openExternal(url),
  myMinimize: () => ipcRenderer.send("minimize"),
  myClose: () => ipcRenderer.send("quit"),
});
```

Then in my components i can just call things like:
```
window.electron.myMinimize();
```

I think this is a better solution overall to needing to requireNode to get access to the electron APIs.

**Comment by bendemboski** [comment]
@dtolios did you also upgrade to Electron 12 at the same time as upgrading `ember-electron`? Because in Electron 12 [context isolation](https://www.electronjs.org/docs/tutorial/context-isolation#context-isolation) is enabled by default. That would mean that you could require "normal" node modules, but not `electron` itself.

You are correct that the method you are using is Electron's recommendation, and probably the best way to go for your application.

Now that context isolation is enabled by default in the latest Electron, we should probably add some information about it the [relevant ember-electron documentation](https://ember-electron.js.org/docs/guides/development-and-debugging#require-and-requirenode-) section.

@dtolios would you mind trying a quick experiment, and roll back to the state where things weren't working, and then see if disabling context isolation fixes your issue? I'm 90% sure it will, but since this is a first-run experience for users of `ember-electron`, I'd love to triple check that it's the (only) issue you're seeing.

And thanks for bringing this to our attention!

**Comment by dtolios** [comment]
@bendemboski ahhh, yes i did, i should be more careful next time to only upgrade one dependency at a time. I'll try the experiment you mentioned and let you know later today.

**Comment by dtolios** [comment]
Apologies for the delay. You were right about disabling context isolation @bendemboski 

With electron 12, ember-electron 3.0.0, and the following browserWindow options, everything worked as before:

```
mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true,
    },
  });
```

We can close this issue since both solutions would work here, and hopefully if anyone else runs across this, the recommended "preload" script method helps point them in a direction where they don't need to requireNode in their apps!

**Comment by bendemboski** [comment]
@dtolios great, thanks a lot for confirming that! I've opened #769 updating the documentation to cover context isolation. If you see anything missing or any improvements that would have better helped you figure out what was going on, feel free to comment on that PR.
